Fixes #35888 - Full host image fails with bad request
theforeman/foreman_bootdisk pull request #139
Opened 2022-12-22 14:22 UTC by stejskalleos

2023-01-02 11:55 UTC, ares requested changes
I'm not necessarily requesting changes, just answers :-)

2023-01-02 11:55 UTC, ares commented on app/services/foreman_bootdisk/iso_generator.rb
> +          response = http_object.get_response(uri)
the `Accept-Encoding` was added for this reason https://projects.theforeman.org/issues/25992, does it now work even without?

2023-01-02 11:55 UTC, ares commented on app/services/foreman_bootdisk/iso_generator.rb
> +            response.body do |chunk|
does body actually accept a block? the docs says differently, internally it calls read_body without passing a block or any argument

2023-01-03 14:43 UTC, stejskalleos commented
Found the issue, problem was in missing `use_ssl=true` for `uri` with `https` scheme

2023-01-03 15:07 UTC, ares approved these changes
Thanks, fixes the issue. Merging!

2023-01-03 15:07 UTC, merged