i18n - pulling from tx
theforeman/foreman_bootdisk pull request #148
Opened 2023-09-18 12:02 UTC by stejskalleos

2023-09-20 09:35 UTC, ekohl reviewed
There is no mechanism to push translations back from source to Transifex. The best way is to change it in Transifex, either via the UI or upload an updated .po file. Then pull again.

2023-09-20 09:35 UTC, ekohl commented on locale/fr/foreman_bootdisk.po
> +msgstr "Impossible de générer le modèle de disque, le modèle%{kind} est introuvable."
Looks like this was intended
```suggestion
msgstr "Impossible de générer le modèle de disque, le modèle %{kind} est introuvable."
```

2023-09-20 09:35 UTC, ekohl commented on locale/ja/foreman_bootdisk.po
> +msgstr "%%{file} が読み取り可能であることを確認します (または「Grub2 ディレクトリー」設定を更新します)"
The `%%{TAG}` appears to be a repeating problem. I think I've also seen this in Transifex, so it isn't some pulling problem.

2023-10-04 07:09 UTC, stejskalleos commented
@ekohl updated the PR

2023-10-04 10:39 UTC, ekohl requested changes
As for Japanese, I think it's best to fix it up in Transifex. Let me know if you need help with that.

2023-10-04 10:39 UTC, ekohl commented on app/assets/javascripts/foreman_bootdisk/locale/fr/foreman_bootdisk.js
> +        "Impossible de générer le modèle de disque, le modèle%{kind} est introuvable."
This line is correct in the .po file. I wonder why it's no longer in sync.

2023-10-05 10:02 UTC, stejskalleos commented
@ekohl I don't have permissions to edit strings in transifex, could you please add me to the project?

2023-10-05 10:57 UTC, ekohl commented
I can't quite figure that out right now (the permission screens are not intuitive), so I quickly fixed it up myself. I'd expect that if you pull again, it is correct.

2023-10-11 06:19 UTC, stejskalleos commented
@ekohl updated

2023-10-11 08:11 UTC, ekohl commented
I still see the same problems. In the past I've seen some issues where I needed to run the command multiple times, probably because it didn't register the timestamp changes properly.

2023-10-11 10:01 UTC, stejskalleos commented
>  I needed to run the command multiple times

Which one exactly? The one in the plugin or the two in the foreman?

2023-10-11 10:18 UTC, ekohl commented
Good question. I used https://github.com/ekohl/theforeman-plumbing/blob/master/bulk-locale-update and I just reran that whole script. Didn't dive deeper. I think my script is now outdated since it doesn't call the JS bits, so be warned.

2023-11-23 11:48 UTC, ekohl commented
Apologies for not paying attention to this for a while. When I now pull myself I don't see the `%%TAG` issue anymore so I think if you pull again, it should be correct.

2023-12-01 09:01 UTC, stejskalleos commented
let's continue in https://github.com/theforeman/foreman_bootdisk/pull/151

2023-12-01 09:01 UTC, closed without merging