Fix Gemspec/RequiredRubyVersion cop
theforeman/foreman_bootdisk pull request #153
Opened 2024-01-17 20:41 UTC by archanaserver

2024-01-23 15:21 UTC, ekohl requested changes
Please rephrase the commit message and PR title to describe the actual code change.

2024-01-26 07:43 UTC, evgeni approved these changes

2024-01-29 08:17 UTC, stejskalleos approved these changes

2024-01-29 08:18 UTC, merged

2024-01-29 08:18 UTC, stejskalleos commented
Thanks everyone!